[target.x86_64-pc-windows-msvc]
#rustflags = ["-Ctarget-feature=+crt-static"]
linker = "lld"
rustflags = [
  "-C", "link-arg=/SUBSYSTEM:WINDOWS",
  "-C", "link-arg=/MACHINE:X64",
  "-Ctarget-feature=+crt-static",
  "-Lnative=/home/$USER/.xwin/crt/lib/x86_64",
  "-Lnative=/home/$USER/.xwin/crt/lib/um/x86_64",
  "-Lnative=/home/$USER/.xwin/crt/lib/ucrt/x86_64"
]
[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-args=/NODEFAULTLIB:MSVCRT"]
[target.'cfg(target_os="macos")']
rustflags = [
    "-C", "link-args=-sectcreate __CGPreLoginApp __cgpreloginapp /dev/null",
]
#[target.'cfg(target_os="linux")']
# glibc-static required, this may fix https://github.com/rustdesk/rustdesk/issues/9103, but I do not want this big change
# this is unlikely to help also, because the other so files still use libc dynamically
#rustflags = [
#    "-C", "link-args=-Wl,-Bstatic -lc -Wl,-Bdynamic"
#]
[net]
git-fetch-with-cli = true

[target.aarch64-linux-android]
linker = "$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang"
